### ISSUE TITLE
ERR:75 & error: lost 36 events

### ISSUE THREAD

**Issue by xumn3348** [wkz/ply#35]
test case:

# cat syscalls_sys_enter_close.ply 
#!/usr/bin/env ply

tracepoint:syscalls/sys_enter_close
{
     printf(" fd:%v\n", data->fd);
}

the last output is like this:

error: lost 36 events
error: lost 36 events
ERR:75

i read the buffer_loop in buffer.c,  i guess "poll "has Inferior performance than "epoll". or the buffer overflows.  or  because of perf 's cost(why not ftrace?)

buffer_q_drain:

(gdb) p *(q->mem)
$29 = {version = 0, compat_version = 0, lock = 4, index = 0, offset = 0, time_enabled = 2078963, time_running = 2078963, {capabilities = 2, {
      cap_bit0 = 0, cap_bit0_is_deprecated = 1, cap_user_rdpmc = 0, cap_user_time = 0, cap_user_time_zero = 0, cap_____res = 0}}, pmc_width = 48,
  time_shift = 0, time_mult = 0, time_offset = 0, time_zero = 0, size = 96, __reserved = '\000' <repeats 947 times>, data_head = 8152,
  data_tail = 4064, data_offset = 4096, data_size = 4096, aux_head = 0, aux_tail = 0, aux_offset = 0, aux_size = 0}

**Comment by wkz** [comment]
Well, basically your script is generating more data than ply can keep up with. By default ply will then exit rather than providing incomplete data; you can override this behavior with the `-k` option.

In general, using `print`/`printf` for these kinds of hot paths is not very useful. I would suggest trying to either filter the output using some predicate (e.g. are you only interested in a particular `comm`/`pid`) or aggregate the data (e.g. `tracepoint:syscalls/sys_enter_close { @[data->fd] = count(); }`).

#### Re: `poll(2)` vs. `epoll(7)`
Could you elaborate on the inferior performance of `poll(2)`? There is one fd per cpu in the poll set, so unless you are on a _massive_ machine, I don't really see how that would matter much.

#### Re: perf vs ftrace
Not sure what you are referring to. The code uses perf events because that was the mechanism available at the time this code was written. Nowadays you could also use a bpf ring buffer, but I fail to see how this relates to ftrace.

**Comment by xumn3348** [comment]
thanks for your perfect replying.

poll(2) vs. epoll(7): 
Although both sleep and alternate, select and poll need to traverse the entire FD set when they are "awake", while epoll only needs to judge whether the ready list is empty when they are "awake", which saves a lot of CPU time. This is the performance improvement brought by the callback mechanism.

perf vs ftrace：
you are right. BPF ringbuf is  gooder than perfbuf. maybe i mistake ftrace for  BPF .

**Comment by wkz** [comment]
I understand how epoll works. I just don't know if I buy the argument that traversing a small array is the limiting factor here. You would have to measure of course, but my guess would be that you are limited by whatever medium you are writing the output to (tty/disk/whatever).

Anyway, if I ever get around to improving this code, it will be to replace the perf event with a bpf ring buffer. In that case the poll set will shrink down to 1, so poll will most likely continue to work just fine.
